
services:
  etcd1:
    image: gcr.io/etcd-development/etcd:${ETCD_VER}
    container_name: node1
    volumes:
      - ./${DATA_DIR}/node1:/${DATA_DIR}
    command: >
      /usr/local/bin/etcd
      --name etcd1
      --data-dir /${DATA_DIR}
      --listen-client-urls http://0.0.0.0:2379
      --advertise-client-urls http://etcd1:2379
      --listen-peer-urls http://0.0.0.0:2380
      --initial-advertise-peer-urls http://etcd1:2380
      --initial-cluster etcd1=http://etcd1:2380,etcd2=http://etcd2:2380
      --initial-cluster-token tkn
      --initial-cluster-state new
      --log-level info
      --logger zap
      --log-outputs stderr
    networks:
      - etcdnet

  etcd2:
    image: gcr.io/etcd-development/etcd:${ETCD_VER}
    container_name: node2
    volumes:
      - ./${DATA_DIR}/node2:/${DATA_DIR}
    command: >
      /usr/local/bin/etcd
      --name etcd2
      --data-dir /${DATA_DIR}
      --listen-client-urls http://0.0.0.0:2379
      --advertise-client-urls http://etcd2:2379
      --listen-peer-urls http://0.0.0.0:2380
      --initial-advertise-peer-urls http://etcd2:2380
      --initial-cluster etcd1=http://etcd1:2380,etcd2=http://etcd2:2380
      --initial-cluster-token tkn
      --initial-cluster-state new
      --log-level info
      --logger zap
      --log-outputs stderr
    networks:
      - etcdnet




networks:
  etcdnet:
    driver: bridge


